<a href="https://colab.research.google.com/github/naoya1110/nitkc-ncku-ai-robotics/blob/main/Week01_Introduction_to_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this AI Robotics Lab course, we will be using PyTorch for implementing deep neural networks. In this notebook we will learn basic functions of PyTorch. So let's get used to it.


## Torch.Tensor
First we need to import PyTorch.

In [1]:
import torch

PyTorch handles multi-dimensional array data as `torch.tensor`. To make a `torch.tensor` data, we pass a Python `list` data to `torch.tensor()`.

In [2]:
a = [1, 2, 3]           # create list named "a"

print(a)                # show "a"
print(type(a))          # show data type of "a"

[1, 2, 3]
<class 'list'>


In [3]:
a = torch.tensor(a)     # convert list "a" to torch.tensor "a"

print(a)
print(type(a))

tensor([1, 2, 3])
<class 'torch.Tensor'>


Also a `torch.tensor` data can be made from a `numpy.ndarray` data.

In [4]:
import numpy as np               # import Numpy package, "np" is abbreviation for numpy

b = np.array([0.4, 0.5, 0.6])    # create a np.ndarray named "b"
b = torch.tensor(b)              # convert np.ndarry "b" to torch.tensor "b"

print(b)
print(type(b))

tensor([0.4000, 0.5000, 0.6000], dtype=torch.float64)
<class 'torch.Tensor'>


It is also possible to convert a `torch.tensor` to a `numpy.ndarray`.

In [5]:
c = b.numpy()        # convert torch.tensor data "b" to np.ndarray data "c"

print(c)
print(type(c))

[0.4 0.5 0.6]
<class 'numpy.ndarray'>


To know the shape of torch.tensor data, there are 2 different ways. One is `.shape` and the other is `.size()` but they return same result.

In [6]:
print(a.shape)
print(a.size())

torch.Size([3])
torch.Size([3])


## Simple Calculations

Now let's do some simple numerical calculations with a `torch.tensor` and a number.

In [7]:
a = torch.tensor([1, 2, 3])
print("a =", a)

print("a+1=", a+1)    # addition
print("a-2=", a-2)    # subtraction
print("a*3=", a*3)    # multiplication
print("a/4=", a/4)    # division

a = tensor([1, 2, 3])
a+1= tensor([2, 3, 4])
a-2= tensor([-1,  0,  1])
a*3= tensor([3, 6, 9])
a/4= tensor([0.2500, 0.5000, 0.7500])


calculations with two `torch.tensor`s.

In [8]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([0.4, 0.5, 0.6])

print("a =", a)
print("b =", b)

print("a+b=", a+b)
print("a-b=", a-b)
print("a*b=", a*b)
print("a/b=", a/b)

a = tensor([1, 2, 3])
b = tensor([0.4000, 0.5000, 0.6000])
a+b= tensor([1.4000, 2.5000, 3.6000])
a-b= tensor([0.6000, 1.5000, 2.4000])
a*b= tensor([0.4000, 1.0000, 1.8000])
a/b= tensor([2.5000, 4.0000, 5.0000])


## PyTorch and Numpy

Since PyTorch is based on Numpy, they have a lot of similarities. If you are already familier with Numpy, you might feel confortable with PyTorch as well. Let's see some examples.

**Zeros Array** - all zero array with given shape

In [9]:
np.zeros(3)    # 1D np.ndarray with 3 zeros

array([0., 0., 0.])

In [10]:
torch.zeros(3) # 1D torch.tensor with 3 zeros

tensor([0., 0., 0.])

In [11]:
torch.zeros((2, 3)) # 2D torch.tensor with 2x3 zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

**Ones Array** - all one array with given shape

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
torch.ones(5)

tensor([1., 1., 1., 1., 1.])

**Random Number Array** - an array of rundom numbers between 0.0 and 1.0 with given shape

In [14]:
np.random.rand(3)

array([0.77745275, 0.61468204, 0.79396784])

In [15]:
torch.rand(3)

tensor([0.7941, 0.7204, 0.3667])

**Arange Array** - 1D array with evenly spaced values

In [16]:
np.arange(1, 5, 1)    # np.arange(start, stop, step) --- stop is not included

array([1, 2, 3, 4])

In [17]:
torch.arange(1, 5, 1)

tensor([1, 2, 3, 4])

In [18]:
torch.arange(5)     # start and step parameters can be omitted

tensor([0, 1, 2, 3, 4])

**Argmax** - returns the index of element with the maximum value in given data

In [19]:
d = np.random.rand(5)

print("d=", d)
print("argmax(d) =", np.argmax(d))    # Remenber: index number starts from 0 in Python

d= [0.64901819 0.73019601 0.91152243 0.24281121 0.53067256]
argmax(d) = 2


In [20]:
d = torch.rand(5)

print("d=", d)
print("argmax(d) =", torch.argmax(d))

d= tensor([0.5036, 0.8084, 0.7636, 0.3968, 0.8133])
argmax(d) = tensor(4)


**Slicing** - take a part of data from original array by specifying indexes

In [21]:
e = np.arange(10) 
print(e)
print(e[2:5])    # take data from index 2 to before index 5

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]


In [22]:
e = torch.arange(10)
print(e)
print(e[2:5])    # take data from index 2 to before index 5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([2, 3, 4])


In [23]:
f = torch.arange(100).view(10,10)    # 10x10 torch.tensor
print(f)
print(f[1:3, 4:8])   # take 2D data from 10x10 torch.tensor

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])
tensor([[14, 15, 16, 17],
        [24, 25, 26, 27]])


There are also differences between PyTorch and Numpy. One of them is the method for reshaping the array data.

**Reshaping** 

In order to reshape the `numpy.ndarray`, we can use `.reshape()`.

In [24]:
g = np.arange(10) # 1D data
g.reshape(2,5)    # reshape data into 2x5 np.ndarray

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In PyTorch we need to use `.view()` instead of `.reshape()`.

In [25]:
f = torch.arange(10)
f.view(2,5)   # reshape data into 2x5 torch.tensor

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

## AutoGrad
One of the most important features of PyTorch is automatic differentiation package `torch.autograd`. PyTorch performs calculation with a computation graph, and this allows us to access the gradients of outputs with respect to the inputs. This is the key for training neural networks.

Let's see a simple example of $y=2x+5$, where $x$ is input and $y$ is output.

In order to enable` torch.autograd` function, we need to set parameters of input `x` as `dtype=torch.float32`,  `requires_grad=True`.

In [26]:
x = torch.tensor(3.0, dtype=torch.float32, requires_grad=True)
y = 2*x + 5
print("y=", y)

y= tensor(11., grad_fn=<AddBackward0>)


As you see above `y` is a torch.tensor data. You can take the value of `y` by `y.item()`.

In [27]:
y.item()

11.0

The gradients of `y` is calculated by `y.backward()`

In [28]:
y.backward()

Now the gradient of `y` respect to `x`, namely $dy/dx$, can be accessed by `x.grad`.

In [29]:
print("dy/dx =", x.grad)

dy/dx = tensor(2.)


**Practice**


1.   Define a new `torch.tensor` $x=5.0$
2.   Do calculation of $y=x^2 + 3x + 1$
3.   Determine the gradient of $dy/dx$ and check if that is correct.

In [30]:
# write code by yourself


**Practice**


1.   Define a new `torch.tensor` $x=3.0$ and $y=2.0$
2.   Do calculation of $z=x^2 + 2y^3$
3.   Determine the partial gradients of $\partial z/\partial x$, $\partial z/\partial y$

In [31]:
# write code by yourself


In deep learning the gradient values are used for optimizing parameters of neural network models by using so-called stochastic gradient descent (SGD) method. As we have seen above PyTorch calculates the gradients of torch.tensors automatically. This is why PyTorch is used for deep learning programming.