<a href="https://colab.research.google.com/github/naoya1110/nitkc-ncku-ai-robotics/blob/main/Week01_Introduction_to_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this AI Robotics Lab course, we will be using PyTorch for implementing deep neural networks. Let's get used to it.

First we need to import PyTorch.

In [1]:
import torch

PyTorch can handle multi-dimensional array data as `torch.tensor`. To make a `torch.tensor` data, we can simply pass a python `list` data to `torch.tensor()`.

In [2]:
a = torch.tensor([1, 2, 3])    # create a torch.tensor data named "a"
print(a)                               # show "a"
print(type(a))                      # show data type of "a"

tensor([1, 2, 3])
<class 'torch.Tensor'>


Also a `torch.tensor` data can be made from a `numpy.ndarray` data.

In [3]:
import numpy as np                   # import numpy package

b = np.array([0.4, 0.5, 0.6])      # create a numpy.ndarray data named "b"
b = torch.from_numpy(b)          # convert numpy.ndarray data "b" to torch.tensor data "b"
print(b)                                    # show "b"
print(type(b))                           # show data type of "b"

tensor([0.4000, 0.5000, 0.6000], dtype=torch.float64)
<class 'torch.Tensor'>


It is also possible to convert a `torch.tensor` to a `numpy.ndarray`.

In [4]:
c = b.numpy()                  # convert torch.tensor data "b" to numpy.ndarray data "c"
print(c)
print(type(c))

[0.4 0.5 0.6]
<class 'numpy.ndarray'>


To know the shape of torch.tensor data, there are 2 different ways. One is `.shape` and other is `.size()` but results are same.

In [5]:
print(a.shape)
print(a.size())

torch.Size([3])
torch.Size([3])


Let's do some simple numerical calculations with a `torch.tensor` and a number.

In [6]:
a = torch.tensor([1, 2, 3])
print("a =", a)
print(a+1)
print(a-2)
print(a*3)
print(a/4)

a = tensor([1, 2, 3])
tensor([2, 3, 4])
tensor([-1,  0,  1])
tensor([3, 6, 9])
tensor([0.2500, 0.5000, 0.7500])


Also calculations with two `torch.tensor`s.

In [7]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([0.4, 0.5, 0.5])

print("a =", a)
print("b =", b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

a = tensor([1, 2, 3])
b = tensor([0.4000, 0.5000, 0.5000])
tensor([1.4000, 2.5000, 3.5000])
tensor([0.6000, 1.5000, 2.5000])
tensor([0.4000, 1.0000, 1.5000])
tensor([2.5000, 4.0000, 6.0000])


PyTorch and Numpy have a lot of similarities. If you are already familier with Numpy, you might feel confortable with PyTorch as well. Let's see some examples.

Zeros Array

In [8]:
torch.zeros(3)    # create an all zero array with given shape

tensor([0., 0., 0.])

Ones Array

In [9]:
torch.ones(3)    # create an all one array with given shape

tensor([1., 1., 1.])

Arange Array

In [10]:
torch.arange(1, 5, 1)    # create evenly spaced values

tensor([1, 2, 3, 4])

Random Number Array

In [11]:
torch.rand(3)    # create random numbers between 0.0 and 1.0 with given shape

tensor([0.6673, 0.5773, 0.4075])

Argmax

In [12]:
a = torch.rand(5)
print(a)
torch.argmax(a) # returns the index of element with the maximum value in given data

tensor([0.4937, 0.0206, 0.7928, 0.3578, 0.5560])


tensor(2)

Slicing data with index

In [13]:
d = np.arange(10)
print(d)
print(d[2:5])    # take data from index 2 to before index 5

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]


There are also differences between PyTorch and Numpy. One of them is reshaping the array data.

In order to reshape the `numpy.ndarray`, we can use `.reshape()`.

In [14]:
a = np.arange(10)
a.reshape(2,5)    # reshape data into 2x5

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In PyTorch we use `.view()` instead of `.reshape()`.

In [15]:
a = torch.arange(10)
a.view(2,5)   # reshape data into 2x5

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

One of the most important features of PyTorch is the differential calculation engine `torch.autograd`. PyTorch performs calculation with a computation graph, and this allows us to access the gradients of outputs with respect to the inputs. This is the key for training neural networks.

In order to enable` torch.autograd` function, we set the parameter of `requires_grad=True` in `torch.tensor`.

Let's do a simple calculation of $y=wx+b$, where $w, x, b$ are inputs and $y$ is output.

Note that `torch.tensor` data have to be floating point number when we set `requires_grad=True` .

In [16]:
w = torch.tensor(2.0, requires_grad=True)
x = torch.tensor(3.0, requires_grad=True)
b = torch.tensor(1.0, requires_grad=True)
y = w*x +b
print(y)

tensor(7., grad_fn=<AddBackward0>)


As you see above `y` is a torch.tensor data. You can take the value of `y` by `y.item()`.

In [17]:
y.item()

7.0

The gradients of $y$ can be calculated by `y.backward()`

In [18]:
y.backward()

Then we can access to the gradients of output respect to the each input.

For example, $dy/dx$ can be accessed by `x.grad`.

In [19]:
print("dy/dx =", x.grad)

dy/dx = tensor(2.)


Also $dy/dw$ and $dy/db$,

In [20]:
print("dy/dw =", w.grad)
print("dy/db =", b.grad)

dy/dw = tensor(3.)
dy/db = tensor(1.)


In training process of deep learning, we have optimize parameters of neural network models in respose to the obtained gradients. However thanks to PyTorch we don't have to update the parameters by ourselves, but PyTorch could do for us.  